### ISSUE TITLE
Windows & Ubuntu 16.04 jupyterlab error - ERROR: Service 'notebook' failed to build : The command '/bin/sh -c pip3 install jupyterlab' returned a non-zero code: 1

### ISSUE THREAD

**Issue by BrickBross** [wesleyraptor/streamingphish#9]
Hi,

have tried across centos, ubuntu & windows but get the following error every time

ERROR: Service 'notebook' failed to build : The command '/bin/sh -c pip3 install jupyterlab' returned a non-zero code: 1

**some more context:**

Removing intermediate container 5361eab4e053
 ---> ec8ad7adfacf
Step 4/11 : RUN pip3 install --upgrade pip
 ---> Running in cd5fb326f327
Collecting pip
  Downloading https://files.pythonhosted.org/packages/de/47/58b9f3e6f611dfd17fb8bd9ed3e6f93b7ee662fb85bdfee3565e8979ddf7/pip-21.0-py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-21.0
Removing intermediate container cd5fb326f327
 ---> b0c119c6d9ea
Step 5/11 : RUN pip3 install jupyterlab
 ---> Running in 34870067d772
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
ERROR: Service 'notebook' failed to build : The command '/bin/sh -c pip3 install jupyterlab' returned a non-zero code: 1

**Comment by OsintUK** [comment]
Was you able to resolve this @BrickBross ?
